### PR TITLE
enhancement: detect more than one UI library

### PR DESCRIPTION
**Pull request by astagi**
## Types of changes

- [ ] New Detector
- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Description
This PR allows vue-telemetry-analyzer to detect more than one UI library. In case you're using Oruga on your website you can use other UI libraries in combination with it, e.g. Oruga + Tailwind or Oruga + Buefy. Test it on [https://passporterapp.com/itineraries](https://passporterapp.com/itineraries)

### CODE REVIEW

**Comment by Atinux** [comment]
Thanks @astagi 

Actually this is quite tricky since in our database we support only one value for the UI library as well as the framework. Also we display only one UI in the listing for each showcase.

This changes will have to updated both the Api and extension also, and at the moment it is not in the priority list sorry.

**Comment by astagi** [comment]
Yeah, no problem! That's why I marked this change as "breaking". Thank you @Atinux for keeping it opened, in future we may have to deal with other CSS agnostic UI libraries (e.g. https://github.com/tailwindlabs/headlessui) and they would be "penalized" using a single field for UI.

**Comment by astagi** [comment]
Hey @Atinux! 👋 Happy to see new VueTelescope releases out! 

Do you have any news on this PR? @jtommy and me are still experiencing the same problem: many web sites built with Oruga but marked as "made with TailwindCSS" or other CSS frameworks. I know that the impact is bigger than this little modification, but I'm just curious wether this feature will be included in the roadmap one day!

**Comment by jtommy** [comment]
@Atinux I think the main "problem" is Tailwind CSS.
In my opinion, it is a disadvantage to see it the UI Framework list/plugins because there are UI libraries that use or can use it, for example Oruga and VueTailwind and often Vue Telescope detects only Tailwind CSS.
What do you think to create a new category for Tailwind CSS or to implement a priority list?
For example when the plugin detects Tailwind and a UI library it shows only the last.

**Comment by Atinux** [comment]
We could have TailwindCSS as the lowest priority indeed, detecting Oruga first and keeping it could be enough :)

**Comment by jtommy** [comment]
It would be awesome 😉

**Comment by jtommy** [comment]
@Atinux are you going to work on by yourself or do you need a new PR?

**Comment by Atinux** [comment]
You can send a PR

**Comment by jtommy** [comment]
@Atinux https://github.com/nuxtlabs/vue-telescope-analyzer/pull/68 😉

**Comment by astagi** [comment]
Thank you @Atinux

**Pull request closed without merging**
